In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('Customer_Shopping_Behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [9]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [10]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [11]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

## Change All the columns to lowercase and replace space with hyphen

In [12]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df = df.rename(columns= {'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

## CREATE A NEW COLUMNS FOR AGE GROUP

In [14]:
labels = ['Young Adult', 'Adult', 'Middle-Aged','Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels)

In [15]:
df[['age','age_group']]

      age    age_group
0      55  Middle-Aged
1      19  Young Adult
2      50  Middle-Aged
3      21  Young Adult
4      45  Middle-Aged
...   ...          ...
3895   40        Adult
3896   52  Middle-Aged
3897   46  Middle-Aged
3898   44        Adult
3899   52  Middle-Aged

[3900 rows x 2 columns]

### Create a new columns for purchase_frequency_days

In [16]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually' : 365,
    'Every 3 months': 90
    
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                        14.0            Fortnightly
1                        14.0            Fortnightly
2                         7.0                 Weekly
3                         7.0                 Weekly
4                       365.0               Annually
...                       ...                    ...
3895                      7.0                 Weekly
3896                     14.0              Bi-Weekly
3897                     90.0              Quarterly
3898                      7.0                 Weekly
3899                     90.0              Quarterly

[3900 rows x 2 columns]

In [18]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

## DROP THE PROMO CODE USED COLUMNS BECAUSE ITS CONTAIN THE SAME INFORMATION THAT DISCOUNT APPLIED CONTAIN

In [19]:
df = df.drop('promo_code_used', axis =1)

In [20]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [21]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\mohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import mysql.connector

try:
    # Database se connection banane ki koshish
    connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="Mohit@7065",
        database="customer_behaviour_analysis"
    )

    if connection.is_connected():
        print("Mubarak ho! MySQL se connection successfully ho gaya hai! 🎉")
        
except mysql.connector.Error as err:
    # Agar MySQL me koi dikkat aayi (jaise password galat ya server off) toh ye error dega
    print(f"Connection nahi ho paaya. Error: {err}")

finally:
    # Connection close karna best practice hai
    if 'connection' in locals() and connection.is_connected():
        connection.close()
        print("MySQL connection safely close ho gaya hai.")

Mubarak ho! MySQL se connection successfully ho gaya hai! 🎉
MySQL connection safely close ho gaya hai.

In [23]:
!pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in C:\Users\mohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: mysql-connector-python in C:\Users\mohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (26.7.0)
Requirement already satisfied: greenlet>=1 in C:\Users\mohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\mohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)

In [24]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# 1. Apna connection URL safe tareeke se banayein (Special character password ke liye best hai)
url_object = URL.create(
    "mysql+mysqlconnector",
    username="root",
    password="Mohit@7065",
    host="localhost",
    database="customer_behaviour_analysis"
)

# 2. Engine banayein (Yeh Pandas ko SQL se jodne ka pull/bridge hai)
engine = create_engine(url_object)

try:
    # 3. DataFrame (df) ko SQL database mein bhejein
    # 'customer_data' aapki nayi table ka naam hoga SQL mein (Aap isse badal sakte hain)
    # if_exists='replace' ka matlab hai ki agar table pehle se hai toh purani hata kar nayi daal de (Aap 'append' bhi use kar sakte hain)
    # index=False ka matlab hai ki df ke index (0,1,2..) ko SQL mein alag column nahi banayega
    
    df.to_sql(name='customer_data', con=engine, if_exists='replace', index=False)
    
    print("Badhai ho! Aapka DataFrame successfully MySQL mein transfer ho gaya hai! 🚀")

except Exception as e:
    print(f"Koi error aayi: {e}")

Badhai ho! Aapka DataFrame successfully MySQL mein transfer ho gaya hai! 🚀